# Adventure game 
print('Welcome to Santa Cruz Adventure Game!')
print('**************************************')
print('You are visiting Santa Cruz, California.')
print('You go on a evning hike alone in the mountains.')
print('You can pick one item to bring with you -')
print('map(m), flashlight(f), chocolate(c), rope(r) or stick(s)')
item = input('What do you choose?: ')
print('You head a humming sound.')
choice_1 = input('Do you follow the sound? Enter Y or n: ')
if choice_1 == 'y':
    print('You keep moving closer to the sound.')
    print('The sound suddenly stops.')
    print('You are now LOST! ...')
    print('You try to call on your phone, but there is no signal!')
else:
    print('Good idea. You are not taking risks.') 
    print('You start walking back to the starting point.')
    print('You realize you are LOST! ')
    print('The sound is behind you and its getting louder. You panic!')
action = input('Do you start running(r) or stop to make a call(c): ')
while action == 'c':
    print('The call does not go through.')
    action = input('Do you start running(r) or stop to make a call(c): ')
print('You are running fast. The sound gets really loud.')
print(' A woman on an electric scooter comes behind you.')
question = input('She asks, Name my favorite computer programming language.: ')
if question == 'Python' | 'python':
    print('She says, Yes Python is my favorite computer programming language.')
print('If you have some chocolate, I can help you.')
print('Luckily , you did ckoose correctly!')
print('You give her the chocolate.')
print('She helps you get home.')
print('CONGRATULATIONS! You got out safely. You won the game.')